# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170424_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='givingRightsDate',
            field=models.DateField(blank=True, help_text='Describes when rights were given', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grantor',
            field=models.ForeignKey(blank=True, help_text='Describes who gave rights for user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
