# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 18:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170501_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('kind', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='medicines',
            field=models.ManyToManyField(to='main.Medicine'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=None, help_text="Exact user's address.", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='locality',
            field=models.CharField(default=None, help_text="Indicates the user's place of residence.", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zipCode',
            field=models.CharField(default=None, help_text='Zip code as complement to the address.', max_length=6, validators=[django.core.validators.RegexValidator(code='Nieprawidlowy kod pocztowy.', message='Kod pocztowy musi byc w odpowiednim formacie: 99-999.', regex='^\\d{2}-\\d{3}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantityInPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PackageQuantity'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='use',
            field=models.TextField(max_length=264),
        ),
        migrations.DeleteModel(
            name='MedicineUse',
        ),
    ]
