# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 16:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipCode', models.CharField(help_text='Zip code as complement to the address.', max_length=6, validators=[django.core.validators.RegexValidator(code='Nieprawidlowy kod pocztowy.', message='Kod pocztowy musi byc w odpowiednim formacie: 99-999.', regex='^\\d{2}-\\d{3}$')])),
                ('locality', models.CharField(help_text="Indicates the user's place of residence.", max_length=64)),
                ('address', models.TextField(help_text="Exact user's address.", max_length=256)),
                ('phoneNumber', models.CharField(blank=True, help_text='Phone number of the company.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='Nieodpowiedni format numeru telefonu', message='Numer telefonu musi byc w odpowiednim formacie, np.: [+99](999 999 999)|(999 99 99).', regex='^\\+?\\d{9,15}$')])),
                ('birthDate', models.DateField(help_text='Birth date of the user.')),
                ('isPharmacist', models.BooleanField(default=False)),
                ('givingRightsDate', models.DateField(blank=True, help_text='Describes when rights were given', null=True)),
                ('grantor', models.ForeignKey(blank=True, help_text='Describes who gave rights for user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CustomUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='grantor',
        ),
        migrations.AlterField(
            model_name='order',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
