# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='producent',
            new_name='producer',
        ),
    ]
