# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 15:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170528_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(code='Nieprawidlowy adres email', message='Wprowadz prawidlowy adres email')])),
                ('zipCode', models.CharField(help_text='Zip code as complement to the address.', max_length=6, validators=[django.core.validators.RegexValidator(code='Nieprawidlowy kod pocztowy.', message='Kod pocztowy musi byc w odpowiednim formacie: 99-999.', regex='^\\d{2}-\\d{3}$')])),
                ('locality', models.CharField(help_text="Indicates the user's place of residence.", max_length=64)),
                ('address', models.TextField(help_text="Exact user's address.", max_length=256)),
                ('phoneNumber', models.CharField(blank=True, help_text='Phone number of the company.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='Nieodpowiedni format numeru telefonu', message='Numer telefonu musi byc w odpowiednim formacie, np.: [+99](999 999 999)|(999 99 99).', regex='^\\+?\\d{9,15}$')])),
                ('birthDate', models.DateField(help_text='Birth date of the user.')),
                ('password', models.CharField(help_text="User's password to application in encoded form.", max_length=128)),
                ('isPharmacist', models.BooleanField(default=False)),
                ('givingRightsDate', models.DateField(blank=True, help_text='Describes when rights were given', null=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Date of last login to the application.', null=True)),
                ('grantor', models.ForeignKey(blank=True, help_text='Describes who gave rights for user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='grantor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
