# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170529_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validityPeriod', models.DateField(help_text='The term of validity of mentioned medicine.')),
                ('imagePath', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('use', models.TextField(max_length=264)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MedicineForm')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='form',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='imagePath',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantityInPackage',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantityInWarehouse',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='use',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='validityPeriod',
        ),
        migrations.AddField(
            model_name='properties',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Medicine'),
        ),
        migrations.AddField(
            model_name='properties',
            name='quantityInPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PackageQuantity'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Warehouse'),
            preserve_default=False,
        ),
    ]
