# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170530_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineform',
            name='form',
            field=models.CharField(choices=[('PILL', 'pill'), ('OINTMENT', 'ointment'), ('INJECTION', 'injection'), ('AEROSOL', 'aerosol'), ('CORE', 'core')], max_length=15),
        ),
    ]
