# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170603_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='application',
            field=models.ManyToManyField(to='main.MedicineApplication'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='composition',
            field=models.ManyToManyField(help_text='Many-to-many field', to='main.Substance'),
        ),
    ]
