# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170603_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='form',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='quantityInPackage',
        ),
        migrations.AddField(
            model_name='medicine',
            name='form',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.MedicineForm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='imagePath',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantityInPackage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.PackageQuantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='use',
            field=models.TextField(default=None, max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='validityPeriod',
            field=models.DateField(default=None, help_text='The term of validity of mentioned medicine.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='application',
            field=models.CharField(help_text='For example: HEAD, STOMACH, ALLERGY', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicineform',
            name='form',
            field=models.CharField(help_text='For example: PILL, OINTMENT, INJECTION, AEROSOL', max_length=50),
        ),
        migrations.AlterField(
            model_name='substance',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
    ]
