# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170607_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='withPrescription',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='medicineapplication',
            name='application',
            field=models.CharField(help_text='For example: HEAD, STOMACH, ALLERGY', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicineform',
            name='form',
            field=models.CharField(help_text='For example: PILL, OINTMENT, INJECTION, AEROSOL', max_length=50, unique=True),
        ),
    ]
