# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170607_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isPharmacist',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
